name: Bug report
description: Bug report template.
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: 'Before you open an issue, please verify if a similar one already exists or has been closed before. More details about the process of contributing can be found in [CONTRIBUTING.md](https://github.com/TheAlgorithms/JavaScript/blob/master/CONTRIBUTING.md).'
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what was the expected behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: Describe what actually happens.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: List steps to reproduce the behavior.
      placeholder: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Specifications
      description: List steps to reproduce the behavior.
      placeholder: |
        1. Version:
        2. Platform:
        3. Browser:
    validations:
      required: false
