name: Node CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        find . -name '*.js' -not -path './node_modules/*' -print0 | xargs -0 -n 1 npx doctest || true  # TODO: Add all doctests
        npx standard
        npm run build --if-present
        npm test
      env:
        CI: true
